version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/pre_loaders/angular-*"
    schedule:
      interval: daily
    labels:
      - dependencies
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      onecx:
        applies-to: version-updates
        patterns:
        - "@onecx*"
        update-types:
        - "minor"
        - "patch"
    ignore:
      - dependency-name: "nx*"
      - dependency-name: "@nx*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - docker-image
