version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/pre_loaders/angular-*"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
    labels:
      - dependencies
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
      onecx:
        applies-to: version-updates
        patterns:
        - "@onecx*"
        update-types:
        - "minor"
        - "patch"
      testing:
        applies-to: version-updates
        patterns:
          - "jasmine*"
          - "karma*"
          - "@types/jasmine"
          - "protractor"
          - "cypress"
          - "@cypress/*"
        update-types:
          - "minor"
          - "patch"
      linting:
        applies-to: version-updates
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
          - "tslint*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        applies-to: version-updates
        patterns:
          - "webpack*"
          - "@types/*"
          - "typescript"
          - "@angular-architects/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "nx*"
      - dependency-name: "@nx*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - docker-image
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
    labels:
      - github-actions
      - dependencies
